name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  compile:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Frontend Syntax Check
        run: |
          cd Application-Code/frontend
          find . -name "*.js" -exec node --check {} \;

      - name: Backend Syntax Check
        run: |
          cd Application-Code/backend
          find . -name "*.js" -exec node --check {} \;

  gitleaks-scan:
    runs-on: self-hosted
    needs: compile

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Gitleaks Setup
        uses: gitleaks/gitleaks-action@v2

      - name: Gitleaks Scan
        run: |
          gitleaks detect --source ./Application-Code/frontend --exit-code 1
          gitleaks detect --source ./Application-Code/backend --exit-code 1

  trivy_fs_scan:
    runs-on: self-hosted
    needs: gitleaks-scan
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: 'fs'
          format: 'table'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
