name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  compile:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Frontend Syntax Check
        run: |
          cd Application-Code/frontend
          find . -name "*.js" -exec node --check {} \;

      - name: Backend Syntax Check
        run: |
          cd Application-Code/backend
          find . -name "*.js" -exec node --check {} \;

  gitleaks-scan:
    runs-on: self-hosted
    needs: compile
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Gitleaks Setup
        uses: gitleaks/gitleaks-action@v2

      - name: Gitleaks Scan
        run: |
          gitleaks detect --source ./Application-Code/frontend --exit-code 1
          gitleaks detect --source ./Application-Code/backend --exit-code 1

  trivy_fs_scan:
    runs-on: self-hosted
    needs: gitleaks-scan
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: 'fs'
          format: 'table'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

  sonar-frontend:
    runs-on: self-hosted
    needs: trivy_fs_scan
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: SonarQube Scan (frontend)
        uses: sonarsource/sonarqube-scan-action@master
        with:
          projectBaseDir: Application-Code/frontend
          args: >
            -Dsonar.projectKey=myorg_frontend
            -Dsonar.projectName=myorg_frontend
            -Dsonar.sources=.
            -Dsonar.exclusions=**/node_modules/**,**/dist/**,**/build/**
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

  sonar-backend:
    runs-on: self-hosted
    needs: sonar-frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: SonarQube Scan (backend)
        uses: sonarsource/sonarqube-scan-action@master
        with:
          projectBaseDir: Application-Code/backend
          args: >
            -Dsonar.projectKey=myorg_backend
            -Dsonar.projectName=myorg_backend
            -Dsonar.sources=.
            -Dsonar.exclusions=**/node_modules/**,**/dist/**,**/build/**
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

  docker-frontend-build-and-push:
    runs-on: ubuntu-latest
    needs: sonar-backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ap-south-1 \
          | docker login --username AWS --password-stdin 352326956023.dkr.ecr.ap-south-1.amazonaws.com

      - name: Build and Push Frontend Docker Image
        uses: docker/build-push-action@v6
        with:
          context: Application-Code/frontend
          push: true
          tags: 352326956023.dkr.ecr.ap-south-1.amazonaws.com/frontend-repo:latest
          file: Application-Code/frontend/Dockerfile

  docker-backend-build-and-push:
    runs-on: ubuntu-latest
    needs: docker-frontend-build-and-push
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ap-south-1 \
          | docker login --username AWS --password-stdin 352326956023.dkr.ecr.ap-south-1.amazonaws.com

      - name: Build and Push Backend Docker Image
        uses: docker/build-push-action@v6
        with:
          context: Application-Code/backend
          push: true
          tags: 352326956023.dkr.ecr.ap-south-1.amazonaws.com/backend-repo:latest
          file: Application-Code/backend/Dockerfile

  ecs-deploy:
    runs-on: ubuntu-latest
    needs: docker-backend-build-and-push
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Deploy Frontend Service to ECS
        run: |
          aws ecs update-service \
            --cluster three-tier-cluster \
            --service frontend-service \
            --force-new-deployment

      - name: Deploy Backend Service to ECS
        run: |
          aws ecs update-service \
            --cluster three-tier-cluster \
            --service backend-service \
            --force-new-deployment
